### ISSUE TITLE
View not Found – yii\base\ViewNotFoundException The view file does not exist: /Applications/MAMP/htdocs/barber/frontend/themes/newlook/views/standard/standard/home-page.php

### ISSUE THREAD

**Issue by dammy23** [yumpee/yumpeecms#1]
After setting up a template, i kept this error message "View not Found – yii\base\ViewNotFoundException
The view file does not exist: /Applications/MAMP/htdocs/barber/frontend/themes/newlook/views/standard/standard/home-page.php".
How can i fix it?

**Comment by tinycall** [comment]
When installing a new theme you can resolve this by either of the following
(1) Go to System->Settings and set the home page to a new home page 
(2) Go to Extensions->View and write into the Home Page view.

Basically because its a new theme, YumpeeCMS needs to know what the default home page of that theme should be. The Blog installation which is usually downloaded sets this default home page for the default theme
